server:
  port: ${SERVER_PORT:8082}

grpc:
  server:
    port: ${GRPC_SERVER_PORT:9092}

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29093}
    properties:
      security.protocol: PLAINTEXT
    admin:
      auto-create-topics: true
    consumer:
      group-id: kpo
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
