CREATE TABLE energy_system (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    battery_level DOUBLE PRECISION NOT NULL,
    low_battery_threshold DOUBLE PRECISION NOT NULL,
    max_battery DOUBLE PRECISION NOT NULL,
    min_battery DOUBLE PRECISION NOT NULL
);

CREATE TABLE satellite_constellation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE satellite (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    constellation_id BIGINT REFERENCES satellite_constellation(id) ON DELETE CASCADE,
    energy_id BIGINT UNIQUE REFERENCES energy_system(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    status_message VARCHAR(255)
);

CREATE TABLE communication_satellite (
    id BIGINT PRIMARY KEY REFERENCES satellite(id) ON DELETE CASCADE,
    bandwidth DOUBLE PRECISION NOT NULL -- Теперь поле не может быть NULL!
);

CREATE TABLE imaging_satellite (
    id BIGINT PRIMARY KEY REFERENCES satellite(id) ON DELETE CASCADE,
    resolution DOUBLE PRECISION NOT NULL,
    photos_taken INTEGER NOT NULL
);

CREATE INDEX idx_satellite_constellation_id ON satellite(constellation_id);
CREATE INDEX idx_satellite_type ON satellite(satellite_type);
CREATE INDEX idx_satellite_name ON satellite(name);
