// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/expect.js";
import "./libs/shim/urijs.js";
import { group, sleep, check } from "k6";

export let options = {
  maxRedirects: 4,
  stages: [
    { duration: '25s', target: 50 },
    { duration: '25s', target: 100 },
    { duration: '25s', target: 100 },
    { duration: '10s', target: 0 }
  ],
  thresholds: {
    http_req_failed: ['rate<0.05'],
    http_req_duration: ['p(95)<2000']
  }
};

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  collection: {
    baseUrl: "http://localhost:8080",
    constellationId: "",
    commSatelliteId: "",
    imgSatelliteId: "",
    commEnergySystemId: "",
    imgEnergySystemId: "",
    constellationName: "",
    imgSatelliteName: "",
    commSatelliteName: ""
  }
});

export default function () {
  const vuId = __VU;
  const iter = __ITER;
  const suffix = `${__VU}-${__ITER}-${Date.now()}`;
  const uniqueImgName = `ImgSat-${suffix}`;
  const uniqueCommName = `CommSat-${suffix}`;
  const uniqueConstName = `TestConstellation-${suffix}`;
  let localCommSatelliteId = null;
  let localImgSatelliteId = null;
  let localCommEnergySystemId = null;
  let localImgEnergySystemId = null;
  let localConstellationId = null;
  let localConstellationName = null;


  group("api", function () {
    postman[Request]({
      name: "create Constellation",
      id: "35de3fbf-4fc0-4293-8aa6-9db301759101",
      method: "POST",
      address: "{{baseUrl}}/api/constellations",
      data: `{\n  "name": "${uniqueConstName}"\n}`,
      headers: {
        "Content-Type": "application/json",
        Accept: "*/*"
      },
      post(response) {
        check(response, { 'HTTP status is 201': (r) => r.status === 201 });

        pm.test("Status code is 201", function () {
          pm.response.to.have.status(201);
        });

        pm.test("Valid JSON in response", function () {
          var jsonData = pm.response.json();
          pm.expect(jsonData)
            .to.have.property("id")
            .that.is.a("number");
          pm.expect(jsonData)
            .to.have.property("constellationName")
            .that.is.a("string")
            .and.equals(uniqueConstName);
          pm.expect(jsonData)
            .to.have.property("satellites")
            .that.is.an("array").and.is.empty;

          localConstellationId = jsonData.id;
          localConstellationName = jsonData.constellationName;

          pm.collectionVariables.set("constellationId", jsonData.id);
          pm.collectionVariables.set("constellationName", jsonData.constellationName);
        });
      }
    });

    postman[Request]({
      name: "get All Constellations",
      id: "e0562dfa-0efc-4fd3-acde-5e5788589e3a",
      method: "GET",
      address: "{{baseUrl}}/api/constellations",
      headers: {
        Accept: "*/*"
      },
      post(response) {
        pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
        });

        pm.test("Valid JSON in response", function () {
          var jsonData = pm.response.json();
          pm.expect(jsonData).to.be.an("array");

          if (jsonData.length > 0) {
            var firstItem = jsonData[0];
            pm.expect(firstItem)
              .to.have.property("id")
              .that.is.a("number");
            pm.expect(firstItem)
              .to.have.property("constellationName")
              .that.is.a("string");
            pm.expect(firstItem)
              .to.have.property("satellites")
              .that.is.an("array");
          }
        });
      }
    });

    postman[Request]({
      name: "create Satellite (img)",
      id: "5a9845d7-313b-4c59-a7db-0d10a3f62d85",
      method: "POST",
      address: "{{baseUrl}}/api/satellites",
      data: `{\n  "type": "IMAGE",\n  "name": "${uniqueImgName}",\n  "batteryLevel": 1.0,\n  "resolution": 30\n}`,
      headers: {
        "Content-Type": "application/json",
        Accept: "*/*"
      },
      post(response) {
        pm.test("Status code is 201", function () {
          pm.response.to.have.status(201);
        });

        pm.test("Valid JSON in response", function () {
          var jsonData = pm.response.json();

          pm.expect(jsonData)
            .to.have.property("id")
            .that.is.a("number");
          pm.expect(jsonData)
            .to.have.property("name")
            .that.is.a("string");
          pm.expect(jsonData)
            .to.have.property("temperatureInside")
            .that.is.a("number");
          pm.expect(jsonData)
            .to.have.property("temperatureOutside")
            .that.is.a("number");
          pm.expect(jsonData)
            .to.have.property("resolution")
            .that.is.a("number");
          pm.expect(jsonData)
            .to.have.property("photosTaken")
            .that.is.a("number");

          pm.expect(jsonData)
            .to.have.property("state")
            .that.is.an("object");
          pm.expect(jsonData.state)
            .to.have.property("statusMessage")
            .that.is.a("string");
          pm.expect(jsonData.state)
            .to.have.property("active")
            .that.is.a("boolean");

          pm.expect(jsonData)
            .to.have.property("energy")
            .that.is.an("object");
          pm.expect(jsonData.energy)
            .to.have.property("id")
            .that.is.a("number");
          pm.expect(jsonData.energy)
            .to.have.property("batteryLevel")
            .that.is.a("number");

          localImgSatelliteId = jsonData.id;
          if (jsonData.energy && jsonData.energy.id) {
            localImgEnergySystemId = jsonData.energy.id;
          }

          pm.collectionVariables.set("imgSatelliteId", jsonData.id);
          pm.collectionVariables.set("imgSatelliteName", jsonData.name);
          pm.collectionVariables.set("imgEnergySystemId", jsonData.energy.id);
        });
      }
    });

    postman[Request]({
      name: "create Satellite (comm)",
      id: "8aec9ec2-9299-408f-a23c-f73cae3c7a9c",
      method: "POST",
      address: "{{baseUrl}}/api/satellites",
      data: `{\n  "type": "COMMUNICATION",\n  "name": "${uniqueCommName}",\n  "batteryLevel": 1.0,\n  "bandwidth": 150\n}`,
      headers: {
        "Content-Type": "application/json",
        Accept: "*/*"
      },
      post(response) {
        pm.test("Status code is 201", function () {
          pm.response.to.have.status(201);
        });

        pm.test("Valid JSON in response", function () {
          var jsonData = pm.response.json();

          pm.expect(jsonData)
            .to.have.property("id")
            .that.is.a("number");
          pm.expect(jsonData)
            .to.have.property("name")
            .that.is.a("string");
          pm.expect(jsonData)
            .to.have.property("temperatureInside")
            .that.is.a("number");
          pm.expect(jsonData)
            .to.have.property("temperatureOutside")
            .that.is.a("number");
          pm.expect(jsonData)
            .to.have.property("bandwidth")
            .that.is.a("number");

          pm.expect(jsonData)
            .to.have.property("state")
            .that.is.an("object");
          pm.expect(jsonData.state)
            .to.have.property("statusMessage")
            .that.is.a("string");
          pm.expect(jsonData.state)
            .to.have.property("active")
            .that.is.a("boolean");

          pm.expect(jsonData)
            .to.have.property("energy")
            .that.is.an("object");
          pm.expect(jsonData.energy)
            .to.have.property("id")
            .that.is.a("number");
          pm.expect(jsonData.energy)
            .to.have.property("batteryLevel")
            .that.is.a("number");

          localCommSatelliteId = jsonData.id;
          if (jsonData.energy && jsonData.energy.id) {
            localCommEnergySystemId = jsonData.energy.id;
          }

          pm.collectionVariables.set("commSatelliteId", jsonData.id);
          pm.collectionVariables.set("commSatelliteName", jsonData.name);
          pm.collectionVariables.set(
            "commEnergySystemId",
            jsonData.energy.id
          );
        });
      }
    });

    postman[Request]({
      name: "get All Satellites",
      id: "2437356b-77c6-49a5-a1e6-e01c3d314ec8",
      method: "GET",
      address: "{{baseUrl}}/api/satellites",
      headers: {
        Accept: "*/*"
      },
      post(response) {
        pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
        });

        pm.test("Valid JSON in response", function () {
          var jsonData = pm.response.json();
          pm.expect(jsonData).to.be.an("array");

          if (jsonData && jsonData.length > 0) {
            var firstItem = jsonData[0];
            pm.expect(firstItem)
              .to.have.property("id")
              .that.is.a("number");
            pm.expect(firstItem)
              .to.have.property("name")
              .that.is.a("string");
            pm.expect(firstItem)
              .to.have.property("temperatureInside")
              .that.is.a("number");
            pm.expect(firstItem)
              .to.have.property("temperatureOutside")
              .that.is.a("number");

            pm.expect(firstItem)
              .to.have.property("state")
              .that.is.an("object");
            pm.expect(firstItem.state)
              .to.have.property("statusMessage")
              .that.is.a("string");
            pm.expect(firstItem.state)
              .to.have.property("active")
              .that.is.a("boolean");

            pm.expect(firstItem)
              .to.have.property("energy")
              .that.is.an("object");
            pm.expect(firstItem.energy)
              .to.have.property("id")
              .that.is.a("number");
            pm.expect(firstItem.energy)
              .to.have.property("batteryLevel")
              .that.is.a("number");
          }
        });
      }
    });

    postman[Request]({
      name: "add Satellite (comm) To Constellation",
      id: "fdace1a3-c869-4f31-af9e-c02119c3dcf2",
      method: "POST",
      address: `${pm.variables.get("baseUrl")}/api/constellations/${localConstellationId}/satellites`,
      data: `{\n  "satelliteId": ${localCommSatelliteId}\n}`,
      headers: {
        "Content-Type": "application/json"
      },
      post(response) {
        pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
        });
      }
    });

    postman[Request]({
      name: "add Satellite (img) To Constellation",
      id: "bb44ab10-d0eb-492f-9d41-5df21627fbfa",
      method: "POST",
      address: `${pm.variables.get("baseUrl")}/api/constellations/${localConstellationId}/satellites`,
      data: `{\n  "satelliteId": ${localImgSatelliteId}\n}`,
      headers: {
        "Content-Type": "application/json"
      },
      post(response) {
        pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
        });
      }
    });

    postman[Request]({
      name: "overview",
      id: "f53dc1cd-6687-47a8-9ac3-aca5c1d442a1",
      method: "GET",
      address: "{{baseUrl}}/api/overview",
      headers: {
        Accept: "*/*"
      },
      post(response) {
        pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
        });

        pm.test("Valid string in response", function () {
          var responseData = pm.response.text();
          pm.expect(responseData).to.include("СИСТЕМНАЯ СВОДКА");
          pm.expect(responseData).to.include("Всего группировок");
        });
      }
    });

    postman[Request]({
      name: "update Satellite",
      id: "fe42d836-2df0-49eb-9962-6213f049bda4",
      method: "PUT",
      address: `${pm.variables.get("baseUrl")}/api/satellites/${localCommSatelliteId}`,
      data: `{\n  "satelliteName": "CommSatUpd-${suffix}"\n}`,
      headers: {
        "Content-Type": "application/json",
        Accept: "*/*"
      },
      post(response) {
        pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
        });

        pm.test("Valid JSON in response", function () {
          var jsonData = pm.response.json();

          var expectedId = localCommSatelliteId ? Number(localCommSatelliteId) : jsonData.id;

          pm.expect(jsonData)
            .to.have.property("id")
            .that.is.a("number")
            .and.equals(expectedId);

          pm.expect(jsonData.name).to.equal(`CommSatUpd-${suffix}`);

          pm.expect(jsonData)
            .to.have.property("state")
            .that.is.an("object");
          pm.expect(jsonData.state)
            .to.have.property("statusMessage")
            .that.is.a("string");
          pm.expect(jsonData.state)
            .to.have.property("active")
            .that.is.a("boolean");

          pm.expect(jsonData)
            .to.have.property("energy")
            .that.is.an("object");
          pm.expect(jsonData.energy)
            .to.have.property("id")
            .that.is.a("number");
          pm.expect(jsonData.energy)
            .to.have.property("batteryLevel")
            .that.is.a("number");

          pm.collectionVariables.set("commSatelliteName", jsonData.name);
        });
      }
    });

    postman[Request]({
      name: "get All Energy Systems",
      id: "c0455386-8cd1-4845-aa67-aba5b48347c0",
      method: "GET",
      address: "{{baseUrl}}/api/energy-systems",
      headers: {
        Accept: "*/*"
      },
      post(response) {
        pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
        });

        pm.test("Valid JSON in response", function () {
          var jsonData = pm.response.json();
          pm.expect(jsonData).to.be.an("array");

          if (jsonData.length > 0) {
            var firstItem = jsonData[0];
            pm.expect(firstItem)
              .to.have.property("id")
              .that.is.a("number");
            pm.expect(firstItem)
              .to.have.property("batteryLevel")
              .that.is.a("number");
            pm.expect(firstItem)
              .to.have.property("lowBatteryThreshold")
              .that.is.a("number");
            pm.expect(firstItem)
              .to.have.property("maxBattery")
              .that.is.a("number");
            pm.expect(firstItem)
              .to.have.property("minBattery")
              .that.is.a("number");
          }
        });
      }
    });

    postman[Request]({
      name: "update Energy System",
      id: "9f3c305c-2af1-432b-9e21-01b9aa4fe46b",
      method: "PUT",
      address: `${pm.variables.get("baseUrl")}/api/energy-systems/${localCommEnergySystemId}`,
      data:
        '{\n  "batteryLevel": 1.0,\n  "lowBatteryThreshold": 0.2,\n  "maxBattery": 1.0,\n  "minBattery": 0.1\n}',
      headers: {
        "Content-Type": "application/json",
        Accept: "*/*"
      },
      post(response) {
        pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
        });

        pm.test("Valid JSON in response", function () {
          var jsonData = pm.response.json();

          var expectedId = localCommEnergySystemId ? Number(localCommEnergySystemId) : jsonData.id;

          pm.expect(jsonData)
            .to.have.property("id")
            .that.is.a("number")
            .and.equals(expectedId);

          pm.expect(jsonData.batteryLevel).to.equal(1.0);
          pm.expect(jsonData.lowBatteryThreshold).to.equal(0.2);
          pm.expect(jsonData.maxBattery).to.equal(1.0);
          pm.expect(jsonData.minBattery).to.equal(0.1);
        });
      }
    });

    postman[Request]({
      name: "execute Mission (single)",
      id: "2c83c412-9949-4312-acbe-3ba5113ef78f",
      method: "POST",
      address: `${pm.variables.get("baseUrl")}/api/missions`,
      data: `{\n  "targetType": "SINGLE",\n  "constellationName": "${localConstellationName}",\n  "satelliteName": "CommSat-${suffix}"\n}\n`,
      headers: {
        "Content-Type": "application/json"
      },
      post(response) {
        pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
        });
      }
    });

    postman[Request]({
      name: "execute Mission (constellation)",
      id: "bcd66101-8908-4695-a1a1-a60ae6337ee3",
      method: "POST",
      address: `${pm.variables.get("baseUrl")}/api/missions`,
      data: `{\n  "targetType": "CONSTELLATION",\n  "constellationName": "${localConstellationName}",\n  "satelliteName": ""\n}\n`,
      headers: {
        "Content-Type": "application/json"
      },
      post(response) {
        pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
        });
      }
    });

    postman[Request]({
      name: "get Constellation By Id",
      id: "d4eb4d67-bd27-41b5-8b0e-db81b49ad836",
      method: "GET",
      address: `${pm.variables.get("baseUrl")}/api/constellations/${localConstellationId}`,
      headers: {
        Accept: "*/*"
      },
      post(response) {
        pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
        });

        pm.test("Valid JSON in response", function () {
          var jsonData = pm.response.json();

          var expectedId = localConstellationId ? Number(localConstellationId) : jsonData.id;
          var expectedName = pm.collectionVariables.get(
            "constellationName"
          );

          pm.expect(jsonData)
            .to.have.property("id")
            .that.is.a("number")
            .and.equals(expectedId);

          pm.expect(jsonData)
            .to.have.property("constellationName")
            .that.is.a("string")
            .and.equals(localConstellationName);

          pm.expect(jsonData)
            .to.have.property("satellites")
            .that.is.an("array");
        });
      }
    });

    postman[Request]({
      name: "get Satellite By Id",
      id: "2876ccf6-96fc-4ef9-ba03-394be97ee26c",
      method: "GET",
      address: `${pm.variables.get("baseUrl")}/api/satellites/${localCommSatelliteId}`,
      headers: {
        Accept: "*/*"
      },
      post(response) {
        pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
        });

        pm.test("Valid JSON in response", function () {
          var jsonData = {};
          if (pm.response.code === 200 || pm.response.code === 201) {
            jsonData = pm.response.json();
          }

          var savedId = pm.collectionVariables.get("commSatelliteId");
          var expectedId = savedId ? Number(savedId) : jsonData.id;

          pm.expect(jsonData)
            .to.have.property("id")
            .that.is.a("number")
            .and.equals(expectedId);

          pm.expect(jsonData)
            .to.have.property("name")
            .that.is.a("string");
          pm.expect(jsonData)
            .to.have.property("temperatureInside")
            .that.is.a("number");
          pm.expect(jsonData)
            .to.have.property("temperatureOutside")
            .that.is.a("number");

          pm.expect(jsonData)
            .to.have.property("state")
            .that.is.an("object");
          pm.expect(jsonData.state)
            .to.have.property("statusMessage")
            .that.is.a("string");
          pm.expect(jsonData.state)
            .to.have.property("active")
            .that.is.a("boolean");

          pm.expect(jsonData)
            .to.have.property("energy")
            .that.is.an("object");
          pm.expect(jsonData.energy)
            .to.have.property("id")
            .that.is.a("number");
          pm.expect(jsonData.energy)
            .to.have.property("batteryLevel")
            .that.is.a("number");
        });
      }
    });

    postman[Request]({
      name: "get Energy System By Id",
      id: "838019c0-b1b7-4de8-a708-bf01811dbcfc",
      method: "GET",
      address: `${pm.variables.get("baseUrl")}/api/energy-systems/${localCommEnergySystemId}`,
      headers: {
        Accept: "*/*"
      },
      post(response) {
        pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
        });

        pm.test("Valid JSON in response", function () {
          var jsonData = pm.response.json();

          var expectedId = localCommEnergySystemId ? Number(localCommEnergySystemId) : jsonData.id;

          pm.expect(jsonData)
            .to.have.property("id")
            .that.is.a("number")
            .and.equals(expectedId);

          pm.expect(jsonData)
            .to.have.property("batteryLevel")
            .that.is.a("number");
          pm.expect(jsonData)
            .to.have.property("lowBatteryThreshold")
            .that.is.a("number");
          pm.expect(jsonData)
            .to.have.property("maxBattery")
            .that.is.a("number");
          pm.expect(jsonData)
            .to.have.property("minBattery")
            .that.is.a("number");
        });
      }
    });

    postman[Request]({
      name: "delete Satellite",
      id: "9a3ef8f4-0baa-45f0-907d-f3b3da8496c6",
      method: "DELETE",
      address: `${pm.variables.get("baseUrl")}/api/satellites/${localImgSatelliteId}`,
      post(response) {
        pm.test("Status code is 204", function () {
          pm.response.to.have.status(204);
        });
      }
    });

    postman[Request]({
      name: "delete Constellation",
      id: "bc967674-fb62-4bdb-abac-1bc49a7d6c69",
      method: "DELETE",
      address: `${pm.variables.get("baseUrl")}/api/constellations/${localConstellationId}`,
      post(response) {
        pm.test("Status code is 204", function () {
          pm.response.to.have.status(204);
        });
      }
    });
  });
}
